server:
  port: 8080
  shutdown: graceful
spring:
  data:
    redis:
      host: localhost
      port: 6379
security:
  oauth2:
    client:
      kakao:
        admin-key: KakaoAdminKey
        client-id: KakaoClientId
        client-secret: KakaoClientSecret
        redirect-uri: http://localhost:8080/v1/oauth2/redirect/kakao
      naver:
        client-id: NaverClientId
        client-secret: NaverClientSecret
        redirect-uri: http://localhost:8080/v1/oauth2/redirect/naver
      apple:
        client-id: AppleClientId
        redirect-uri: http://localhost:8080/v1/oauth2/redirect/apple
        team-id: AppleTeamId
        key-id: AppleKeyId
        key-path: /path/to/AuthKey_AppleKeyId.p8
      google:
        client-id: GoogleClientId
        client-secret: GoogleClientSecret
        redirect-uri: http://localhost:8080/v1/oauth2/redirect/google
      github:
        client-id: GithubClientId
        client-secret: GithubClientSecret
        redirect-uri: http://localhost:8080/v1/oauth2/redirect/github
management:
  server:
    port: 18080
  endpoints:
    web:
      cors:
        allowed-origins: "https://admin.domain.io"
      exposure:
        include:
          - health
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
jwt:
  issuer: https://shcho.io
  secret: Key-For-JWT
service:
  aws:
    access-key: my-access-key
    secret-key: my-secret-key
    region: ap-northeast-1
    s3:
      bucket: bucket-1
      url: https://s3-ap-northeast-1.amazonaws.com/bucket-1
    sns:
      topic-arn: arn:aws:sns:ap-northeast-1:123456789012:topic-1
      android-arn: arn:aws:sns:ap-northeast-1:123456789012:app/GCM/Android-1
      ios-arn: arn:aws:sns:ap-northeast-1:123456789012:app/APNS/IOS-1
    ses:
      from: no-reply@shcho.com

